Create default network policy for shoot
ironcore-dev/gardener-extension-provider-ironcore pull request #673
Opened 2024-12-09 09:57 UTC by ushabelgur

# Proposed Changes

- Add default network policy for shoot with default ingress/egress
- Use label `extension.ironcore.dev/cluster-name` as `NetworkInterfaceSelector` while creating `NetworkPolicy` (Note same label is used while creating `NetworkInterface` in machine controller)
- Add testcases

Fixes #672

2024-12-17 13:17 UTC, afritzler requested changes
We need to take care of deleting the `NetworkPolicy` once the Shoot is being deleted.

2025-01-15 05:10 UTC, ushabelgur commented
> We need to take care of deleting the `NetworkPolicy` once the Shoot is being deleted.

Done, added deletion logic

2025-01-17 08:47 UTC, afritzler reviewed
LGTM. We will merge this for next extension release.

2025-01-17 14:44 UTC, afritzler requested changes
Can we also add to the test case a delete case and ensure that the infrastructure resources have been removed?

2025-01-20 08:56 UTC, ushabelgur commented
> Can we also add to the test case a delete case and ensure that the infrastructure resources have been removed?

I have already updated existing test case to check network policy is being removed when infrastructure is deleted

2025-01-22 16:10 UTC, afritzler approved these changes

2025-01-22 16:11 UTC, merged